Repository vapor/open-crypto, pull requests merged in 2018-05, with the labels that each got.

#61 Fix an IV length error message.
  Sources/Crypto/Cipher/Cipher.swift
Labels: bug

#63 eliminate warnings for Swift 4.1
  Sources/Crypto/Cipher/Cipher.swift
Labels: enhancement

#65 Convert CryptoRandom and OSRandom into structs to save allocations
  Sources/Crypto/Random/CryptoRandom.swift
  Sources/Random/OSRandom.swift
Labels: enhancement

#60 Add several more default cipher algorithms and make initialization with an EVP_CIPHER public
  Sources/Crypto/Cipher/CipherAlgorithm.swift
Labels: enhancement

#67 small fixes before 3.2.0
  Sources/Crypto/BCrypt/BCryptDigest.swift
  Sources/Crypto/RSA/RSA.swift
  Sources/Crypto/RSA/RSAPadding.swift
  Sources/Crypto/Random/CryptoRandom.swift
  Sources/Crypto/Utilities/Exports.swift
Labels: bug, enhancement
